MOUSEKEY_ENABLE = yes    # Mouse keys
RGBLIGHT_ENABLE = no
OLED_ENABLE     = yes
OLED_DRIVER     = ssd1306
LTO_ENABLE      = yes
WPM_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball
