MOUSEKEY_ENABLE = yes    # Mouse keys
RGBLIGHT_ENABLE = no
OLED_ENABLE     = yes
OLED_DRIVER     = ssd1306
LTO_ENABLE      = yes
WPM_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
BOOTLOADER = atmel-dfu
#CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_2X
#CIRQUE_PINNACLE_POSITION_MODE = CIRQUE_PINNACLE_ABSOLUTE_MODE
